---

- name: install PostgreSQL and related packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ POSTGRES_PKG }}"
  tags:
    - postgres-pkg

- name: create symlink for postgresql
  shell: |
    ln -s /usr/lib/postgresql/13/bin/* /usr/bin/
  tags:
    - postgres-symlink
